version: '3.7'
services:
  aura:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
  database:
    build:
      dockerfile: Dockerfile
      context: ./db
    volumes:
    - 'db:/var/lib/data'
volumes:
  db: