version: '3.7'
services:
  aura:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
  database:
    image: mongo:3.6.17
    restart: always
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - 'db:/var/lib/data'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
volumes:
  db: